CREATE EXTENSION IF NOT EXISTS vector;

-- DROP TABLE IF EXISTS wikipedia 

CREATE TABLE IF NOT EXISTS wikipedia (
	id SERIAL PRIMARY KEY,
	title TEXT NOT NULL,
	chunk TEXT NOT NULL,
	embedding VECTOR NOT NULL
)
